name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.7]

steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> $GITHUB_ENV
  - name: Use the value
    id: step_two
    run: |
      echo "${{ env.action_state }}" # This will output 'yellow'
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd atom_ml_django
        pip install -r requirements.txt
        ls -l
      - name: Run tests
      run: 
        cd atom_ml_django
        python manage.py runserver
